### ISSUE TITLE
Bug: causes server to hang on shutdown

### ISSUE THREAD

**Issue by Aaronstar-McClure** [enjarai/show-me-your-skin#38] opened 2023-05-11 03:05 UTC
im not sure why, but when we have v1.6.3 installed server side, the server is unable to finish shutting down/restart. ill send logs and modlist in a moment

minecraft 1.19.2, fabric loader 0.14.19

**Comment by Aaronstar-McClure** [comment] 2023-05-11 03:15
[latest.log](https://github.com/enjarai/show-me-your-skin/files/11447736/latest.log)

<details>
  <summary>Modlist</summary>

Loading 329 mods:
	- advdebug 2.3.0
	- alternate-current 1.5.0
	- amecs 1.3.8+mc.1.19-rc2
	   \-- amecsapi 1.3.6+mc22w17a
	- angling 1.0.1
	- another_furniture 2.1.2-1.19.2
	- appleskin 2.4.1+mc1.19
	- architectury 6.5.82
	- attributefix 17.2.6
	- balm-fabric 4.5.7
	- barteringstation 4.0.3
	- bclib 2.1.6
	- beautify 1.1.1+fabric-1.19.2
	   |-- cardinal-components-base 5.0.2
	   |-- cardinal-components-entity 5.0.2
	   \-- cardinal-components-world 5.0.2
	- bedspreads 6.0.0+1.19.2
	- betteradvancements 0.3.0.148
	- bettercombat 1.7.0+1.19
	- betterdeserttemples 1.19.2-Fabric-2.2.2
	   \-- org_reflections_reflections 0.10.2
	- betterdungeons 1.19.2-Fabric-3.2.1
	- betterend 2.1.4
	- betterfortresses 1.19.2-Fabric-1.0.5
	- betterfpsdist 1.19-2.4
	- bettermineshafts 1.19.2-Fabric-3.2.0
	- betternether 7.1.3
	- betteroceanmonuments 1.19.2-Fabric-2.1.0
	- betterstats 2.6.1+1.19.2
	   \-- tcdcommons 2.6+1.19.2
	- betterstrongholds 1.19.2-Fabric-3.2.0
	- bettervillage 3.0.0
	- betterwitchhuts 1.19.2-Fabric-2.1.0
	- boatbreakfix 1.0.11
	- bookshelf 16.2.18
	- bountiful 3.0.0
	- brewinandchewin fabric-1.0.6+1.19.2
	- bwncr 3.14.1
	- charmofundying 6.2.0+1.19.2
	- chefsdelight 1.0.3-fabric-1.19.2
	   \-- structurized-reborn 1.19-01
	- chipped 2.1.4
	- chisel 1.4.5
	- chunky 1.3.38
	- cinderscapes 3.0.3
	   |-- cinderscapes-client 3.0.3
	   |-- cinderscapes-common 3.0.3
	   |-- cinderscapes-worldgen 3.0.3
	   |-- terraform-biome-remapper-api-v1 4.1.1
	   \-- terraform-shapes-api-v1 4.1.1
	- cloth-api 4.0.65
	   |-- cloth-basic-math 0.6.1
	   |-- cloth-client-events-v0 4.0.65
	   |-- cloth-common-events-v1 4.0.65
	   |-- cloth-scissors-api-v1 4.0.65
	   \-- cloth-utils-v1 4.0.65
	- cloth-config 8.2.88
	   \-- cloth-basic-math 0.6.1
	- clumps 9.0.0+14
	- collective 6.53
	- comforts 6.0.4+1.19.2
	   \-- spectrelib 0.12.4+1.19.2
	- completeconfig 2.1.0
	   |-- coat 1.0.0-beta.19+mc22w17a
	   |-- completeconfig-base 2.1.0
	   |-- completeconfig-gui-cloth 2.1.0
	   |-- completeconfig-gui-coat 2.1.0
	   \-- completeconfig-gui-yacl 2.1.0
	- configured 2.0.0
	- cookingforblockheads 13.3.2
	- corgilib 1.0.0.32
	   |-- com_electronwill_night-config_core 3.6.6
	   \-- com_electronwill_night-config_toml 3.6.6
	- couplings 1.9.1+1.19
	- cpm 0.6.7a
	- craftingbench 0.4-BETA+1.19
	- create 0.5.0.i-1003+1.19.2
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- flywheel 0.6.8.a-4
	   |-- milk 1.0.51
	   |    \-- dripstone_fluid_lib 2.0.1
	   |-- porting_lib 2.1.926+1.19.2
	   |    |-- forge_tags 3.0
	   |    |-- porting_lib_accessors 2.1.926+1.19.2
	   |    |-- porting_lib_attributes 2.1.926+1.19.2
	   |    |-- porting_lib_base 2.1.926+1.19.2
	   |    |-- porting_lib_common 2.1.926+1.19.2
	   |    |-- porting_lib_constants 2.1.926+1.19.2
	   |    |-- porting_lib_entity 2.1.926+1.19.2
	   |    |-- porting_lib_extensions 2.1.926+1.19.2
	   |    |-- porting_lib_fake_players 2.1.926+1.19.2
	   |    |-- porting_lib_lazy_registration 2.1.926+1.19.2
	   |    |-- porting_lib_loot 2.1.926+1.19.2
	   |    |-- porting_lib_model_generators 2.1.926+1.19.2
	   |    |-- porting_lib_model_loader 2.1.926+1.19.2
	   |    |-- porting_lib_models 2.1.926+1.19.2
	   |    |-- porting_lib_networking 2.1.926+1.19.2
	   |    |-- porting_lib_obj_loader 2.1.926+1.19.2
	   |    |-- porting_lib_transfer 2.1.926+1.19.2
	   |    \-- serialization_hooks 0.3.26
	   |-- reach-entity-attributes 2.3.0
	   \-- registrate-fabric 1.1.57-MC1.19.2
	- createaddition 20230508b
	   \-- team_reborn_energy 2.2.0
	- createorigins 1.1.0+1.19.2
	- creeperoverhaul 2.0.9
	- cullclouds 0.1.0
	- culturaldelights 0.14.9+1.19.2
	   \-- terraform-wood-api-v1 4.2.0
	- cyclepaintings 3.2
	- debugify 2.8.0
	- deepslatecutting 1.5.0
	   \-- maybe-data 1.3.2-1.19.2
	- dragonfight 1.19.2-2.8
	- dynview 1.19-2.4
	- easyanvils 4.0.11
	- easymagic 4.3.3
	- ecologics 2.1.11
	- economical_villager_trading 1.2.8
	   \-- crowdin-translate 1.4+1.19
	- editsign 2.6.0
	- effortless 1.6.2
	- enchantinginfuser 4.2.2
	- end_origins 1.0.0
	- enderscape 0.4.1-1.19.2
	   \-- mm 2.3
	- endrem 5.2.0
	- entitycollisionfpsfix 2.0.0.0
	- expandeddelight 0.2.5.2
	- experiencebugfix 19
	- extraorigins 1.19-2
	- fabric-api 0.76.0+1.19.2
	   |-- fabric-api-base 0.4.15+8f4e8eb390
	   |-- fabric-api-lookup-api-v1 1.6.14+93d8cb8290
	   |-- fabric-biome-api-v1 9.1.1+16f1e31390
	   |-- fabric-block-api-v1 1.0.2+e415d50e90
	   |-- fabric-blockrenderlayer-v1 1.1.25+cafc6e8e90
	   |-- fabric-client-tags-api-v1 1.0.5+b35fea8390
	   |-- fabric-command-api-v1 1.2.16+f71b366f90
	   |-- fabric-command-api-v2 2.2.1+413cbbc790
	   |-- fabric-commands-v0 0.2.33+df3654b390
	   |-- fabric-containers-v0 0.1.41+df3654b390
	   |-- fabric-content-registries-v0 3.5.2+7c6cd14d90
	   |-- fabric-convention-tags-v1 1.3.0+4bc6e26290
	   |-- fabric-crash-report-info-v1 0.2.8+aeb40ebe90
	   |-- fabric-data-generation-api-v1 5.3.8+413cbbc790
	   |-- fabric-dimensions-v1 2.1.35+0d0f210290
	   |-- fabric-entity-events-v1 1.5.4+9244241690
	   |-- fabric-events-interaction-v0 0.4.34+562bff6e90
	   |-- fabric-events-lifecycle-v0 0.2.36+df3654b390
	   |-- fabric-game-rule-api-v1 1.0.24+b6b6abb490
	   |-- fabric-item-api-v1 1.6.6+b7d1888890
	   |-- fabric-item-groups-v0 0.3.39+9244241690
	   |-- fabric-key-binding-api-v1 1.0.25+5c4fce2890
	   |-- fabric-keybindings-v0 0.2.23+df3654b390
	   |-- fabric-lifecycle-events-v1 2.2.4+1b46dc7890
	   |-- fabric-loot-api-v2 1.1.13+83a8659290
	   |-- fabric-loot-tables-v1 1.1.16+9e7660c690
	   |-- fabric-message-api-v1 5.0.7+93d8cb8290
	   |-- fabric-mining-level-api-v1 2.1.24+33fbc73890
	   |-- fabric-models-v0 0.3.21+c6af733c90
	   |-- fabric-networking-api-v1 1.2.11+10eb22f490
	   |-- fabric-networking-v0 0.3.28+df3654b390
	   |-- fabric-object-builder-api-v1 4.2.2+d8ef690890
	   |-- fabric-particles-v1 1.0.14+4d0d570390
	   |-- fabric-recipe-api-v1 1.0.1+413cbbc790
	   |-- fabric-registry-sync-v0 0.9.32+9244241690
	   |-- fabric-renderer-api-v1 1.2.1+1adbf27790
	   |-- fabric-renderer-indigo 0.8.0+1adbf27790
	   |-- fabric-renderer-registries-v1 3.2.24+df3654b390
	   |-- fabric-rendering-data-attachment-v1 0.3.19+6e0787e690
	   |-- fabric-rendering-fluids-v1 3.0.11+4d0d570390
	   |-- fabric-rendering-v0 1.1.27+df3654b390
	   |-- fabric-rendering-v1 1.12.1+d8ef690890
	   |-- fabric-resource-conditions-api-v1 2.1.2+aae9039d90
	   |-- fabric-resource-loader-v0 0.8.4+edbdcddb90
	   |-- fabric-screen-api-v1 1.0.32+4d0d570390
	   |-- fabric-screen-handler-api-v1 1.3.7+1cc24b1b90
	   |-- fabric-sound-api-v1 1.0.2+c4f28df590
	   |-- fabric-textures-v0 1.0.24+aeb40ebe90
	   |-- fabric-transfer-api-v1 2.1.6+413cbbc790
	   \-- fabric-transitive-access-wideners-v1 1.3.3+08b73de490
	- fabric-language-kotlin 1.9.4+kotlin.1.8.21
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.21
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.20.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.0
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.0
	- fabricloader 0.14.19
	- factory_blocks 1.0.1+1.19
	- farmersdelight 1.19.2-1.3.9
	- farmersknives 2.4
	- farmersrespite 2.2.4
	- farmingforblockheads 11.3.0
	- faster_entity_animations 1.5.7
	- fastfurnace 1.19.2-5
	- fastload 3.4.0
	   |-- conditional-mixin 0.3.2
	   |-- fastload-119-0-1-2-compat 3.4.0
	   |-- fastload-1193-compat 3.4.0
	   |-- fastload-1194-compat 3.4.0
	   \-- fastload_fapi_forward 1.0.2
	- fdjei 1.0.1
	- ferritecore 5.0.3
	- fixmyspawnr 1.1.3
	- forgeconfigapiport 4.2.11
	- foxboi_two 1.1.9
	- furnish 23
	- geckolib3 3.1.40
	   \-- com_eliotlash_mclib_mclib 20
	- glassential 1.4.0
	- guardvillagers 1.19.2-1.1.2
	- handcrafted 2.0.6
	- hauntedharvest 1.19.2-3.1.5
	- headfix 1.2.0
	- immersive_aircraft 0.4.2+1.19.2
	- inmis 2.7.1-1.19
	   \-- omega-config 1.2.3-1.18.1
	- inmisaddon 1.0.4
	- inventorysorter 1.8.10-1.19
	   \-- kyrptconfig 1.4.14-1.19
	- inventorytotem 3.0
	- ironchests 3.1.1
	- jamlib 0.6.0+1.19
	- java 17
	- jei 11.6.0.1015
	- jeresources 1.2.2.200
	- journeymap 5.9.6
	   \-- journeymap-api-fabric 1.19.1-1.9-fabric-SNAPSHOT
	- justenoughprofessions 2.0.2
	- justmobheads 7.1
	- justplayerheads 3.1
	- kambrik 4.0-1.19.2
	- krypton 0.2.1
	   \-- com_velocitypowered_velocity-native 3.1.2-SNAPSHOT
	- lazydfu 0.1.3
	- libertyvillagers 1.0.14+fabric+1.19.2
	   \-- server_translations_api 1.4.18+1.19.2
	        \-- packet_tweaker 0.3.0+1.18.2
	- libraryferret 4.0.0
	- lithium 0.11.1
	- logbegone 1.0.6
	- memoryleakfix 1.0.0
	   \-- com_github_llamalad7_mixinextras 0.2.0-beta.6
	- midnightlib 1.0.0
	- minecraft 1.19.2
	- mixin-conflict-helper 1.2.0
	- mixintrace 1.1.1+1.17
	- moonlight 1.19.2-2.2.31
	- more_gems 1.4.53
	   \-- pugh_tools 1.3.23
	- morebannerfeatures 1.1.3
	- mousewheelie 1.10.7+mc1.19.2
	   |-- amecsapi 1.3.7+mc22w17a
	   |-- coat 1.0.0-beta.19+mc22w17a
	   |-- fabric-key-binding-api-v1 1.0.22+aaaf9d3390
	   |-- tweed4_annotated 1.3.1+mc22w17a
	   |-- tweed4_base 1.7.1+mc22w17a
	   |-- tweed4_data 1.2.1+mc22w17a
	   |-- tweed4_data_hjson 1.1.1+mc22w17a
	   |-- tweed4_tailor_coat 1.1.3+mc22w17a
	   \-- tweed4_tailor_screen 1.1.3+mc22w17a
	- mru 0.1.5+1.19.2
	   \-- com_sksamuel_scrimage_scrimage-core 4.0.31
	- multibeds 1.3.2
	- musicplayer 2.4.1.17
	- naturalist 3.0.2
	- naturescompass 1.19.2-2.1.0-fabric
	- netherportalfix 10.0.1
	- nethersdelight 1.0.1
	   \-- disable_custom_worlds_advice 3.0
	- nets 0.3.5.2
	- nochatreports 1.19.2-v1.13.12
	   |-- fabric-rendering-v1 1.11.0+73145abb90
	   \-- fabric-screen-api-v1 1.0.27+93d8cb8290
	- oceansdelight 1.0.0
	- onsoulfire 1.19-2
	- origins 1.7.1
	   |-- apoli 2.6.1
	   |    |-- additionalentityattributes 1.0.0+1.19
	   |    |-- calio 1.7.0
	   |    \-- playerabilitylib 1.6.0
	   \-- reach-entity-attributes 2.3.0
	- owo 0.9.3+1.19
	   \-- blue_endless_jankson 1.2.1
	- paradise_lost 2.1.0-beta+1.19.2
	   |-- customportalapi 0.0.1-beta54-1.19
	   |-- gud_recipe_confidence 1.0.2
	   |-- incubus_core 1.9.4
	   |-- reach-entity-attributes 2.3.0
	   \-- satin 1.8.0
	- patchouli 1.19.2-77-FABRIC
	   \-- fiber 0.23.0-2
	- paxi 1.19.2-Fabric-3.0.1
	- pehkui 3.7.3+1.14.4-1.20
	   \-- kanos_config 0.4.0+1.14.4-1.19.4
	- phantomredux 1.0.0+all-versions+fabric
	- phosphor 0.8.1
	- player-animator 1.0.2
	- polymorph 0.46.1+1.19.2
	   \-- cardinal-components-item 5.0.1
	- puzzleslib 4.4.0
	   |-- cardinal-components-base 5.0.2
	   |-- cardinal-components-block 5.0.2
	   |-- cardinal-components-chunk 5.0.2
	   |-- cardinal-components-entity 5.0.2
	   \-- cardinal-components-world 5.0.2
	- realisticbees 3.3
	- realisticfirespread 1.19-2
	- resourcefulconfig 1.0.20
	- resourcefullib 1.1.24
	- rightclickharvest 3.1.1+1.19-1.19.2
	- server_translations 1.4.18+1.19.2
	   |-- packet_tweaker 0.3.0+1.18.2
	   \-- server_translations_api 1.4.18+1.19.2
	        \-- packet_tweaker 0.3.0+1.18.2
	- shetiphiancore 1.3.4
	- showmeyourskin 1.6.3+1.19.2
	   |-- cardinal-components-base 5.0.2
	   |-- cardinal-components-entity 5.0.2
	   \-- cicada 0.4.0
	- simplyswords 1.46.0-1.19.2
	- sit 1.19-20
	- skyvillages 1.0.2.1
	- smallships 2.0.0a1.1.1
	- smarterfarmers 1.19.2-1.7.2
	- smoke_suppression 1.0.13
	   \-- crowdin-translate 1.4+1.19
	- smoothboot 1.19-1.7.1
	- smoothchunk 1.19.1-2.0
	- stendhal 1.3.4-1.19
	   \-- libgui 6.0.0-beta.5+1.19-pre1
	        |-- jankson 4.1.1+j1.2.1
	        \-- libninepatch 1.1.0
	- stoneholm 1.4.4
	- supplementaries 1.19.2-2.3.10
	- suppsquared 1.19.2-1.1.0
	- takesapillage 1.0.4
	- theoneprobe 1.19-6.2.2
	   \-- team_reborn_energy 2.2.0
	- thorium 1.3.2
	   |-- com_typesafe_config 1.4.2
	   |-- io_leangen_geantyref_geantyref 1.3.13
	   |-- org_spongepowered_configurate-core 4.1.2
	   \-- org_spongepowered_configurate-hocon 4.1.2
	- toofast 1.0.0
	- tradingpost 4.2.0
	- trinkets 3.4.2
	- trinkets-curios-theme 0.2.2+1.19
	- uteamcore 4.1.0.10
	- villagerfix 1.0.3
	- villagernames 4.5.1
	   |-- cardinal-components-base 5.0.2
	   \-- cardinal-components-level 5.0.2
	- visualworkbench 4.2.4
	- vmp 0.2.0+beta.7.29
	- walljump-fabric 1.6.1b
	- waystones 11.4.0
	- whyamionfire 1.2.0
	- with_thursday 1.0.1
	- wither_cage_fix 1.0.16
	- xlpackets 1.19.2-4
	- yet-another-config-lib 2.2.0-for-1.19.2
	- yosbr 0.1.1
	- yungsapi 1.19.2-Fabric-3.8.9
	   \-- org_javassist_javassist 3.28.0-GA
	- yungsbridges 1.19.2-Fabric-3.1.0

</details>

**Comment by enjarai** [comment] 2023-06-08 08:42
I haven't been able to recreate this, it could be due to one of your other mods.

**Comment by whatamaniac** [comment] 2023-06-27 20:50
I'm facing the same issue on my server. on 1.19.2 Fabric loader 0.14.21. i won't include it in my server mods as it causes issues while automatic server restarts (have to kill the server... server hangs up).. But i'll still include it in my client modpack as it does the thing without having it on the server. Lemme know if you need my modlist or anything else (logs are clean and it also doesn't generate a crash report).

**Comment by enjarai** [comment] 2023-06-27 20:54
This is really strange, I still haven't been able to reproduce it. The only thing I can think of is some kind of incompatibility between mods. 

If you can send your modlist, I'll try to crossreference it with the one in the original issue to see if there's specific overlap.

**Comment by Aaronstar-McClure** [comment] 2023-06-27 21:09
@whatamaniac 
Yeah, the issue with not including it on server side is that it doesn't copy over settings from client to client. So if a player has a custom skin and a modified model and they have to adjust the sliders to make it work right, all those changes aren't seen by other players, only the one who owns the skin.

**Comment by whatamaniac** [comment] 2023-06-27 22:29
@enjarai here's my server modlist: https://pastebin.com/9VAy3v81
lemme know if you need any other help =]

**Comment by enjarai** [comment] 2023-07-03 17:52
Nothing obvious stands out to me in the information provided, and I still can't recreate this issue, so let's try some other things. Does the issue occur for either of you when only SMYS is installed on the server?

**Comment by Aaronstar-McClure** [comment] 2023-07-04 00:44
I'll have to try it out when I get home. The modpack has been in heavy development for a while since then, but I'll see if I can get an old copy thrown back up

**Comment by whatamaniac** [comment] 2023-07-04 14:44
Well i haven't tried only SMYS but i'll make things easy for you. I'll try to search the culprit thru binary search.. but it'll take me some time.

**Comment by enjarai** [comment] 2023-07-04 15:42
> @enjarai Well i haven't tried only SMYS but i'll make things easy for you. I'll try to search the culprit thru binary search.. but it'll take me some time.

That'll be very helpful, though I would recommend testing if it works with only SMYS first, since it might be something specific to your system rather than modlist.

**Comment by whatamaniac** [comment] 2023-07-04 16:28
> > @enjarai Well i haven't tried only SMYS but i'll make things easy for you. I'll try to search the culprit thru binary search.. but it'll take me some time.
> 
> That'll be very helpful, though I would recommend testing if it works with only SMYS first, since it might be something specific to your system rather than modlist.

Yes yes i'll make sure to install SYMS first and then adding other mods to find the culprit. I'll actually first test with the mods which are in @Aaronstar-McClure Modlist cuz my modlist is way more bigger... so i'll check his modlist cuz we have alot of same mods.

**Comment by Aaronstar-McClure** [comment] 2023-07-04 16:48
Here, I can give you a copy of the pack if you want to look into it. Don't know exactly which version it was, and we were fiddling around with the server a bit trying to bugfix, but I hope this helps.

https://cdn.discordapp.com/attachments/292736538280984576/1125592302308565126/Coactum_SMP_6.0.3.zip
 https://cdn.discordapp.com/attachments/292736538280984576/1125592446450020352/Coactum_SMP_6.0.4.zip

**Comment by ImKringle** [comment] 2023-09-16 12:06
#58 Isolated it to this version specifically, not sure if any others are causing it - but 1.6.3 on 1.19.x is

**Comment by enjarai** [comment] 2023-09-16 15:17
(Crosspost from #58)

This bug originates in a common library I use for my mods called CICADA. Normally you wouldn't have to deal with it, as its included in the jar file, and Fabic will load it from there, but that means to fix it properly, I'll have to push a version of this mod that includes a newer version of CICADA, even if no code from this mod changes. However, if you manually provide a never version of an included library to Fabric, it'll load that instead of the included version.

So long story short, this means you should be able to fix it by adding this jar to your mods folder:
https://maven.enjarai.dev/releases/nl/enjarai/cicada-lib/0.4.4/cicada-lib-0.4.4.jar

It's not on any mod publishing websites, cause it usually doesn't need to be, but feel free to check the source [here](https://github.com/enjarai/cicada-lib).

**Comment by ImKringle** [comment] 2023-09-17 01:20
That did the trick, appreciate you @enjarai 🖖

**Comment by simeonpfeiffer** [comment] 2023-09-20 14:32
I was having the same issue and can confirm that adding cicada lib 0.4.4 solves it. Thank you!

As a sidenote: For me it took some time to track this issue down to this mod, because I was also using C2ME. Using C2ME circumvents this bug, because it has an undocumented feature that terminates jvm after everything is saved.

**Comment by enjarai** [comment] 2024-03-09 16:27
Fixed in all recent versions.

**Closed by enjarai** 2024-03-09 16:27 UTC
