### ISSUE TITLE
Armors sometimes make players transparent over their body.

### ISSUE THREAD

**Issue by astro-angelfish** [enjarai/show-me-your-skin#68] opened 2024-01-17 10:24 UTC
Sometimes the armor are transparent along with the body of the player, like the image below. (Left: me, expected. Right: glitched.)

![image](https://github.com/enjarai/show-me-your-skin/assets/22395490/ec29bde3-0716-432a-aac7-5a34846344fc)

[Entity culling mod](https://modrinth.com/mod/entityculling) or rendering orders are suspected without any evidence. But no exact cause was found. The player at the right of the image got her armor on when I'm not nearby, and she used `/tp` command to get close to me.

Rejoining the server could do a temporary fix.

Full mod list:
```
+---(astro-angelfish@AL-1S)-[/home/astro-angelfish/.minecraft/mods]-[0]
+-$ ls
clientcommands-2.8.5.jar                 krypton-0.2.3.jar                    NoChatReports-FABRIC-1.20.1-v2.2.2.jar    sound-physics-remastered-fabric-1.20.1-1.3.1.jar
cloth-config-11.1.118-fabric.jar         litematica-fabric-1.20.1-0.15.3.jar  notenoughcrashes-4.4.7+1.20.1-fabric.jar  StackDeobfuscatorFabric-1.4.2+bf1fc22.jar
CustomSkinLoader_Fabric-14.19.1.jar      lithium-fabric-mc1.20.1-0.11.2.jar   physics-mod-pro-v164-fabric-1.20.1.jar    tweakeroo-fabric-1.20.1-0.17.1.jar
entityculling-fabric-1.6.2-mc1.20.1.jar  malilib-fabric-1.20.1-0.16.3.jar     show-me-your-skin-1.6.11+1.20.jar         Xaeros_Minimap_23.9.3_Fabric_1.20.jar
fabric-api-0.91.0+1.20.1.jar             minihud-fabric-1.20.1-0.27.0.jar     skinlayers3d-fabric-1.6.2-mc1.20.1.jar    XaerosWorldMap_1.37.2_Fabric_1.20.jar
iris-mc1.20.1-1.6.11.jar                 modmenu-7.2.2.jar                    sodium-fabric-mc1.20.1-0.5.3.jar
```

**Comment by enjarai** [comment] 2024-01-17 10:29
This is a known issue and duplicate of #19. I've looked into it and contacted the iris devs, but there doesn't seem to be anything I can do about it...

**Closed by enjarai** 2024-01-17 10:29 UTC
